# Generated by Django 6.0.7 on 2026-07-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noterelation',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина связи'),
        ),
    ]
