# Generated by Django 6.0.7 on 2026-07-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_noterelation_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='cover',
        ),
    ]
