# Generated by Django 6.0.7 on 2026-07-22 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50, verbose_name='Провайдер (Группа)')),
                ('display_name', models.CharField(max_length=100, verbose_name='Название в интерфейсе')),
                ('model_code', models.CharField(max_length=100, unique=True, verbose_name='Код для API')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступна для выбора')),
            ],
            options={
                'verbose_name': 'Модель ИИ',
                'verbose_name_plural': 'Модели ИИ',
                'ordering': ['provider_name', 'display_name'],
            },
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.AlterField(
            model_name='note',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='ai_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.aimodel', verbose_name='Выбранная модель'),
        ),
    ]
