# Generated by Django 6.0.7 on 2026-07-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_usersettings_user_alter_usersettings_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='ai_model',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='provider',
            field=models.CharField(blank=True, choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('local', 'Локальная модель (Ollama)'), ('claude', 'Anthropic (через OpenRouter)')], max_length=50, verbose_name='Провайдер'),
        ),
        migrations.DeleteModel(
            name='AIModel',
        ),
    ]
